#!/bin/bash

##
## test_name.sh <AVC REGEXP> <DIRECTORY>
##
## Prints names of test cases where logs contained entries matched by
## the passed regexp.
##
## The passed directory where the logs are searched for should have a
## certain structure
## (<DIRECTORY>/<platform>-<timestamp>/<test-case-name>/journal.txt).
## Such structure is generated by download-test-logs.sh script, for
## instance.
##
## The AVC regexp can be taken verbatim from the output of avcs.sh
## script.
##
## Flags:
##
## -h - print this help
##
## Positional parameters:
##
## 0 - AVC denial regexp
## 1 - directory
##

set -euo pipefail

print_help=''

while [[ ${#} -gt 0 ]]; do
    case ${1} in
        -h) print_help=x; shift;;
        --) shift; break;;
        -*) echo "unknown flag ${1}" >&2; exit 1;;
        *) break;;
    esac
done

if [[ -n ${print_help} ]]; then
    grep '^##' "${0}" | sed -e 's/^##[[:space:]]*//'
    exit 0
fi

if [[ ${#} -ne 2 ]]; then
    echo 'expected exactly two positional parameters' >&2
    exit 1
fi

cd "${2}"

grep -nrIHe "${1}" | cut -d/ -f 2 | sort -u
